[build]
  # No build command needed for static HTML/JS
  command = ""
  # Publish the root directory
  publish = "."

# Disable all build plugins
[build.environment]
  NODE_VERSION = "18"

# Explicitly disable extensions
[[plugins]]